/**
 * 9 playable Runners (5F / 4M for variety; user asked 3+3 originally then +3 specialty).
 * Actually: keep 3F+3M original + 3 specialty: Boom (f explosives), Forge (m craft), Wires (f tech/craft)
 * = 5F 4M. User said 3 more with specialties - fine.
 */
export const CHARACTERS = [
  {
    id: 'neon_val',
    name: 'Neon Val',
    gender: 'f',
    title: 'Club Ghost',
    blurb: 'Ex-VIP hostess. A smile opens doors. A bat ends arguments.',
    color: 0xec4899,
    hair: 0xf472b6,
    style: 'glam',
    bonuses: { atk: 1, maxHp: 0, batBonus: 2, sneakBonus: 0, scavengeBonus: 0 },
  },
  {
    id: 'pretty_boy',
    name: 'Pretty Boy',
    gender: 'm',
    title: 'Camera Bait',
    blurb: 'Looks like a poster. Runs like a rumor. Fists are for photos only.',
    color: 0x38bdf8,
    hair: 0xfde68a,
    style: 'slim',
    bonuses: { atk: -1, maxHp: -4, moveBonus: 1, sneakBonus: 1, scavengeBonus: 1, visionDay: 1 },
  },
  {
    id: 'shade',
    name: 'Shade',
    gender: 'f',
    title: 'Roofline Ninja',
    blurb: 'Quiet boots. Long sightlines. Prefers not to be remembered.',
    color: 0x7c3aed,
    hair: 0x1e1b4b,
    style: 'hood',
    bonuses: { visionDay: 2, sneakBonus: 2, rangedBonus: 1 },
  },
  {
    id: 'brick',
    name: 'Brick',
    gender: 'm',
    title: 'Dock Bruiser',
    blurb: 'Built like a loading bay. Takes hits. Gives worse.',
    color: 0xea580c,
    hair: 0x44403c,
    style: 'tank',
    bonuses: { atk: 2, def: 1, maxHp: 10, moveBonus: -1, sneakBonus: -1, batBonus: 1 },
  },
  {
    id: 'doc_rue',
    name: 'Doc Rue',
    gender: 'f',
    title: 'Alley Medic',
    blurb: 'Patch kit in one hand, bad news in the other. Survives on scraps.',
    color: 0x16a34a,
    hair: 0xa3e635,
    style: 'medic',
    bonuses: { maxHp: 6, scavengeBonus: 1, healBonus: 4 },
  },
  {
    id: 'static',
    name: 'Static',
    gender: 'm',
    title: 'Grid Hacker',
    blurb: 'Talks to dead circuits. Hears the city hum. Bad at doors labeled push.',
    color: 0x0891b2,
    hair: 0x22d3ee,
    style: 'tech',
    bonuses: { visionDay: 1, scavengeBonus: 2, craftBonus: 1 },
  },
  {
    id: 'boom',
    name: 'Boom Chi',
    gender: 'f',
    title: 'Demo Queen',
    blurb: 'Ex-mining charges. If it is sealed, she is interested. Loud on purpose.',
    color: 0xdc2626,
    hair: 0xfbbf24,
    style: 'demo',
    bonuses: { atk: 1, maxHp: 2, scavengeBonus: 1, explosiveBonus: 2 },
  },
  {
    id: 'forge',
    name: 'Forge',
    gender: 'm',
    title: 'Scrapwright',
    blurb: 'Welds hope from trash. Crafts faster. Sleeps next to the spark bench.',
    color: 0xd97706,
    hair: 0x78350f,
    style: 'forge',
    bonuses: { def: 1, maxHp: 4, craftBonus: 2, scavengeBonus: 1, moveBonus: -1 },
  },
  {
    id: 'needle',
    name: 'Needle',
    gender: 'f',
    title: 'Wire Saint',
    blurb: 'Circuit prayer. Extra loot from tech trash. Hates dogs, loves drones less.',
    color: 0x4f46e5,
    hair: 0xc4b5fd,
    style: 'wire',
    bonuses: { visionDay: 1, scavengeBonus: 2, craftBonus: 1, sneakBonus: 1, atk: -1 },
  },
];

export function getCharacter(id) {
  return CHARACTERS.find((c) => c.id === id) || CHARACTERS[0];
}
